name: Deploy to Quay

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '30 5 3 * *'
jobs:

  build:

    runs-on: ubuntu-latest
    environment: quay
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      run: |
      docker buildx create --use
    - name: Set date
      id: date
      run: echo "::set-output name=date::$(date +'%m-%d-%Y')"
    - name: Login to quay
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
      run: docker login -u $USERNAME --password-stdin quay.io <<<"$PASSWORD"
    - name: Build the Docker image
      #run: docker build . --file Dockerfile --tag quay.io/cloudonix/syslog-cloudwatch-bridge
      run: docker buildx build --file Dockerfile --platform linux/arm64,linux/amd64 \
        --tag quay.io/cloudonix/syslog-cloudwatch-bridge:${{ steps.date.outputs.date }} \
        --push .
